{% set name = "flake8-pyproject" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/john-hen/Flake8-pyproject/archive/{{ version }}.tar.gz
  sha256: 9075bdd9712b03a9dad78652425081bbee63c9ad759bf9efb3a0eb1cd1b180c3

build:
  noarch: python
  entry_points:
    - "flake8p = flake8p:main"
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=3.4
    - flake8
    - tomli
  run:
    - python >={{ python_min }}
    - flake8 >=5
    - tomli

test:
  imports:
    - flake8p
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/john-hen/Flake8-pyproject
  summary: Flake8 plug-in loading the configuration from pyproject.toml
  license: MIT
  license_file: license.txt

extra:
  recipe-maintainers:
    - rxm7706
