{% set name = "flake8-pyproject" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/john-hen/Flake8-pyproject/archive/refs/tags/1.2.3.tar.gz
  sha256: 8f065721c53c1fe22d423d82db99eef6559b463a8701aa03b03668d43abfc851

build:
  noarch: python
  entry_points:
    - "flake8p = flake8p:main"
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - flit-core >=3.4
    - flake8 >=5
  run:
    - python >=3.7
    - flake8 >=5
    - tomli

test:
  imports:
    - flake8p
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/john-hen/Flake8-pyproject
  summary: Flake8 plug-in loading the configuration from pyproject.toml
  license: MIT
  license_file: license.txt

extra:
  recipe-maintainers:
    - rxm7706
